<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IMCBCP464-MSL1" ignored="0" name="Personal Loan" tests="6" failures="1" timestamp="2020-09-01T21:49:54 IST" time="0.051" errors="0">
  <testcase name="Demo" time="0.007" classname="test.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:20)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="Second" time="0.0" classname="test.day1"/>
  <testcase name="ploan" time="0.001" classname="test.day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.002" classname="test.day4"/>
  <testcase name="MobileloginHomeLoan" time="0.001" classname="test.day4"/>
  <testcase name="WebloginHomeLoan" time="0.001" classname="test.day4"/>
</testsuite> <!-- Personal Loan -->
